
scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle  # Other option is flake8

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 121  # Default is 79 in PEP 8
    ignore:  # Errors and warnings to ignore
        - E731  # do not assign a lambda expression, use a def
        - E402  # module level import not at top of file
