# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.8
env:
  - torch>=1.2,<1.3
  - torch>=1.3,<1.4
  - torch>=1.4,<1.5
  - torch>=1.5,<1.6
  - torch>=1.6,<1.7
  - torch>=1.7,<1.8
  - torch>=1.8,<1.9
  - torch>=1.8

jobs:
  exclude:
  - python: 3.8
    env: torch>=1.2,<1.3
  - python: 3.8
    env: torch>=1.3,<1.4
  include:
  - python: 3.9
    env: torch>=1.8,<1.9
  - python: 3.9
    env: torch>=1.8


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U "$TORCH"
  - python setup.py install

# Command to run tests, e.g. python setup.py test
script:
  # run unit tests
  - py.test
  # run integration tests
  - lettuce --no-cuda convergence
  - lettuce --no-cuda benchmark




