# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.8
  - 3.9
torch:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - python setup.py install

# Command to run tests, e.g. python setup.py test
script:
  # run unit tests
  - tox
  # run integration tests
  - lettuce --no-cuda convergence
  - lettuce --no-cuda benchmark




