name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 7 * * 1"


jobs:
  test:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, python-version: '3.12', torch-version: 'pytorch>=2.4' }
          - { os: windows-latest, python-version: '3.12', torch-version: 'pytorch>=2.4' }
          - { os: macos-latest, python-version: '3.12', torch-version: 'pytorch>=2.4' }

    steps:

      - uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          auto-update-conda: true
          activate-environment: test
          auto-activate-base: false
          python-version: ${{ matrix.cfg.python-version }}
          miniconda-version: "latest"
      - name: Init conda
        run: |
          conda init
      - name: Install dependencies
        run: |
          conda activate test
          conda install "${{ matrix.cfg.torch-version }}" -c pytorch -c nvidia
          conda install --file requirements.txt -c conda-forge -c pytorch -c nvidia
      - name: Test import
        run: |
          python3 -c "import os; print(os.environ); import numpy as np; from setuptools import setup"
      - name: Install lettuce
        run: |
          python3 setup.py install
      - name: Unit tests with pytest
        run: |
          pytest tests
      - name: Integration tests
        run: |
          lettuce --no-cuda convergence --use-no-cuda_native
          lettuce --no-cuda benchmark --use-no-cuda_native
