name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 7 * * 1"


jobs:
  test:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: windows-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: macos-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: ubuntu-latest, python-version: '3.11', torch-version: 'torch>=2.1' }
          - { os: windows-latest, python-version: '3.11', torch-version: 'torch>=2.1' }
          - { os: macos-latest, python-version: '3.11', torch-version: 'torch>=2.1' }

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v3.0.4
      - run: |
          conda install pytorch==2.4 "${{ matrix.cfg.torch-version }}" -c pytorch -c nvidia
          conda install --file requirements.txt -c pytorch -c nvidia -c conda-forge
      - name: Install package
        run: |
          python setup.py install
      - name: Unit tests with pytest
        run: |
          py.test tests
      - name: Integration tests
        run: |
          lettuce --no-cuda convergence --use-no-cuda_native
          lettuce --no-cuda benchmark --use-no-cuda_native
