name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"


jobs:
  test:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: windows-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: macos-latest, python-version: '3.10', torch-version: 'torch>=2.1' }
          - { os: ubuntu-latest, python-version: '3.11', torch-version: 'torch>=2.1' }
          - { os: windows-latest, python-version: '3.11', torch-version: 'torch>=2.1' }
          - { os: macos-latest, python-version: '3.11', torch-version: 'torch>=2.1' }

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "${{ matrix.cfg.torch-version }}" pyevtk h5py mmh3
      - name: Install package
        run: |
          python setup.py install
      - name: Unit tests with pytest
        run: |
          py.test
      - name: Integration tests
        run: |
          lettuce --no-cuda convergence
          lettuce --no-cuda benchmark
